### ISSUE TITLE
Etam reduces average page load time by 700ms and increases conversions by 20%

### ISSUE THREAD

**Issue by andydavies** [tkadlec/WPOStats#1]
## Key Takeaway

Etam reduces it's average page load time from 1.2s to 500ms and increased conversions by 20%, time on site by 21%, and pages viewed per visit by 28%.

## Story Source

http://blog.quanta-computing.com/etam-earns-20-of-conversion-by-optimising-its-online-store/

## Tags

- conversions
- engagement
- page views

**Comment by tkadlec** [comment]
Thanks, @andydavies!
