### ISSUE TITLE
Study Submission:

### ISSUE THREAD

**Issue by andydavies** [tkadlec/WPOStats#10]
## Key Takeaway
The Trainline reduced latency by 0.3 seconds across their funnel and customers spent an extra £8 million ($11.5m) a year. 

## Story Source
https://youtu.be/ai-6qwT6ES8?t=462

## Year published
2016

## Tags
-revenue

**Comment by tammyeverts** [comment]
Andy, this phrasing reads a bit strangely for me: "The Trainline reduced latency by 0.3 of a second".

Could we change it to "The Trainline reduced latency by 0.3 seconds" (which is how I'd put this if I were saying it out loud)?

**Comment by sergeychernyshev** [comment]
It must be British thing ;)

**Comment by andydavies** [comment]
Sure, I'm fine with that - I'd actaully say what out wrote out loud but I can see why you might say it differently

**Comment by tammyeverts** [comment]
It's my weird North American education. ;)
