### ISSUE TITLE
Study Submission:

### ISSUE THREAD

**Issue by arnaso** [tkadlec/WPOStats#12]
## Key Takeaway
- For every 100ms decrease in homepage load speed, Mobify's customer base saw a 1.11% lift in session based conversion, amounting to an average annual revenue increase of $376,789;
- For every 100ms decrease in checkout page load speed, Mobify's customers saw a 1.55% life in session based conversion, amounting to an average annual revenue increase of $526,147;
- Shoppers browse more on faster mobile websites;
- An increase of one pageview per user results in a 5.17% lift in user based conversion, i.e. for each additional page viewed per user, Mobify saw their average customer's annual revenue increase by: $398,484.

## Story Source
http://resources.mobify.com/2016-Q2-mobile-insights-benchmark-report.html?utm_source=MarketWired&utm_medium=Press-Release&utm_campaign=2016q2-mobile-insights-report

## Year published
2016

## Tags
conversions
revenue
engagement
2016

**Comment by tkadlec** [comment]
This is great! I think we might break these up into three different entries—excluding only the third bullet point since it doesn't have any actual stats attached to it. What do you think @tammyeverts?

**Comment by tammyeverts** [comment]
Hey there! I'm on a vacation road trip till next week, with only my phone at hand. I'll defer to your always awesome judgment. :)

**Comment by sergeychernyshev** [comment]
Awesome!
