### ISSUE TITLE
Study Submission:

### ISSUE THREAD

**Issue by jonarnes** [tkadlec/WPOStats#13]
## Key Takeaway

Describes impact of optimizing images in terms of payload but also organizational- and integration related metrics. 
## Story Source

http://www.scientiamobile.com/page/case-study-crazy-factory-optimized-image-delivery
## Year published

2016
## Tags
- list
- of
- appropriate
- tags

**Comment by tkadlec** [comment]
Hey @jonarnes! Sorry we missed this one. 

Can you help me identify the business metrics mentioned? I'm missing them I think.

**Comment by jonarnes** [comment]
@tkadlec Realized after posting this that it's business metrics you're after. In here, there are none. Got a new one coming up though. I'll notify you when it's done.
