### ISSUE TITLE
Is there a typo in the Intuit study summary?

### ISSUE THREAD

**Issue by andydavies** [tkadlec/WPOStats#14]
https://wpostats.com/2015/11/04/intuit-conversions.html

"While reducing page load from 15 seconds to 2 seconds, Intuit saw a 3% improvement in conversions for every second reduced over 7%, and a 2% improvement in conversions for every second reduced over 5 seconds."

Should it be a 3% improvement for every second over 7 seconds, rather than 7%?

**Comment by tkadlec** [comment]
s/tidy/tardy

typos even in the commit messages! :)
