### ISSUE TITLE
Add a '3rd party code' tag (and more 'causes of bad performance' tags)

### ISSUE THREAD

**Issue by wheresrhys** [tkadlec/WPOStats#2]
The 'ads' tag is already a nod towards the impact 3rd party code can have on performance, but a more all-encompassing '3rd party code' (or alternatively several less broad tags e.g. 'tagmanagers', 'tracking', etc...) would make it easier to find case studies about these issues.

More generally, the tags are mostly about things that performance can impact (e.g. bounce rate) rather than things that can impact performance. Depending on why I'm looking for a case study both types of tag could be useful. e.g. whether I'm trying to persuade my boss that performance will benefit the company, or whether I want to persuade them that adding feature X will be bad for performance

Happy to help with the retagging if this sounds like a good idea.

**Comment by tkadlec** [comment]
I would want to be careful that we don't end up with tag soup, but if we can avoid that, I like the idea. :)

**Comment by wheresrhys** [comment]
Yep, tag soup is quite horrible. How about setting a performance budget of a maximum of 5 (or your choice of N) new tags

- 3rd party code
- Ads (could go under 3rd party code)
- Visual design
- Single page apps/Client side frameworks
- Web fonts (though this could easily go under visual design)
- Blocking the critical path (or a broader title could contain anything relating to delivery of resources to the browser)

... are what I came up with in the last few minutes.
