### ISSUE TITLE
Study Submission: COOK case study

### ISSUE THREAD

**Issue by alexpainter** [tkadlec/WPOStats#25]
## Key Takeaway
COOK increased conversion rate by 7% after cutting average page load time by 0.85 seconds. Bounce rate also fell by 7% and pages per session increased by 10%.

## Story Source
https://www.nccgroup.trust/uk/about-us/resources/cook-real-user-monitoring-case-study/?style=Website+Performance&resources=Case+Studies

## Year published
2017

## Tags
- conversion
- engagement
- bounce rate

**Comment by tkadlec** [comment]
Thanks! Tis live https://wpostats.com/2017/11/15/cook-conversion-rate.html

**Comment by alexpainter** [comment]
Thank you!
