### ISSUE TITLE
Study Submission: Voonik image optimization

### ISSUE THREAD

**Issue by jonarnes** [tkadlec/WPOStats#26]
## Key Takeaway
Voonik deployed dynamic image optimization and reduced image payload by more than 60%, saved 95% development time and reduced the page load time by 2-3 seconds.

## Story Source
https://www.scientiamobile.com/page/imageengine-case-study-voonik

## Year published
2017

## Tags
- productivity
- mobile
- payload reduction

**Comment by tammyeverts** [comment]
I removed 'images' and 'page load time' because those aren't biz metrics. I kept 'mobile' though, and I added 'productivity', because I think both of those would be good tags to add.

**Comment by sergeychernyshev** [comment]
Yeah, I don't see business metrics which might make it a good article (although written on vendor's website), but not for WPOStats.

If this sentence had real numbers behind them, this would be a different story:
"Voonik needed a
solution to ... improve conversions, and control future CDN operating costs."
