### ISSUE TITLE
Study Submission: Zalando

### ISSUE THREAD

**Issue by xaprb** [tkadlec/WPOStats#30]
## Key Takeaway
100 msec loading time improvement led to a 0.7% uplift in revenue per session.  

## Story Source
https://jobs.zalando.com/tech/blog/loading-time-matters/index.html

## Year published
2018

**Comment by tkadlec** [comment]
Thanks, @xaprb! Should be live now: https://wpostats.com/2018/06/13/zalando-revenue.html
