### ISSUE TITLE
Study Submission: Radins.com (M6Web Group, France)

### ISSUE THREAD

**Issue by borisschapira** [tkadlec/WPOStats#32]
## Key Takeaway
Compliance with best practices on an editorial site has improved web performance (Speed Index improved by 51% on the desktop). This quickly translated into a significant increase in conversion (+12%) and a drop in the rebound rate (-25%).

Google AMP produces immediate gains quite easily, but the result is no better than a well thought-out optimization (which is 20% faster here). Its only advantage is the leverage effect of the SERP that Google enforces.

## Story Source
https://blog.dareboost.com/en/2018/08/continuous-improvement-web-performance-dareboost-m6web/

## Year published
2018

## Tags
- best practices
- seo
- amp

**Comment by tkadlec** [comment]
Sorry for missing this @borisschapira! Is there a specific perf metric (or a few) you can put in the snippet? Like..."improved X metric by Xs, and saw an increase in conversion..."

**Comment by borisschapira** [comment]
I've update the takeaway with info from the blog post, is it better?
