### ISSUE TITLE
Study Submission: Sparkbox / Driver Solutions

### ISSUE THREAD

**Issue by caralyn** [tkadlec/WPOStats#33]
## Key Takeaway
Web studio Sparkbox more than doubled Driver Solutions’ conversion rate for organic traffic, moving it from 2.69% to 5.57% after deploying performance updates and AMP pages.

## Story Source
https://seesparkbox.com/foundry/driver_solutions_website_load_faster_performance_optimization

## Year published
2018

## Tags
- conversion
- search
- seo
- 2018

**Comment by tkadlec** [comment]
Sorry this took so long, @caralyn. Should be all set!
