### ISSUE TITLE
Out of date link for COOK case study

### ISSUE THREAD

**Issue by alexpainter** [tkadlec/WPOStats#34]
Hi,

NCC Group's web performance division was acquired by Eggplant earlier in 2018, and the old link to the COOK case study (COOK increased conversion rate by 7% after cutting average page load time by 0.85 seconds. Bounce rate also fell by 7% and pages per session increased by 10%.) no longer works. The new URL is https://eggplant.io/case-studies/2018/10/19/cook-increases-conversions-by-seven-percent-thanks-to-faster-load-time

Thanks

**Comment by tkadlec** [comment]
Fixed! Thanks @alexpainter!
