### ISSUE TITLE
Study Submission: GOV.UK

### ISSUE THREAD

**Issue by Nooshu** [tkadlec/WPOStats#35]
## Key Takeaway
Changing the way fonts were loaded on GOV.UK removed 200KB from the browsers critical path resulted in the speed index dropping by 50% for 4G mobiles. Users on slow mobiles using a 2G connection saw pages load 10 seconds faster under these conditions.

## Story Source
[Making GOV.UK pages load faster and use less data](https://gdstechnology.blog.gov.uk/2018/10/04/making-gov-uk-pages-load-faster-and-use-less-data/)

## Year published
2018

## Tags
- font
- viewability
- 2018
- traffic

**Comment by tkadlec** [comment]
This is an awesome case study! The only thing missing for it to be on wpostats is some sort of business metric. Is there anything like views, bounce rate, etc that you can point to?

**Comment by Nooshu** [comment]
Hi @tkadlec, I can take a look but we really don't have many business metrics. Being government, we aren't selling anything and GOV.UK is the only place to find the information we display. Our primary goal is to make accessing this data as quick and painless as possible for all citizens.

I will certainly take a look though.
