### ISSUE TITLE
Study Submission: Abandonment rate on Google Search clicks drops by 20%

### ISSUE THREAD

**Issue by RByers** [tkadlec/WPOStats#40]
## Key Takeaway
When Google Search started using speed as a (very small) ranking signal, they saw a 15%-20% improvement in user-centric perf metrics of pages loaded from search results and a 20% reduction in abandonment.

## Story Source
https://webmasters.googleblog.com/2019/04/user-experience-improvements-with-page.html

## Year published
2019

## Tags
- abandonment
- search

**Comment by tkadlec** [comment]
Up, after an embarrassingly long delay. Sorry @RByers! https://wpostats.com/2020/05/27/google-search-abandonment.html

**Comment by RByers** [comment]
No worries, thanks for getting it up!
