### ISSUE TITLE
Remove the google-mobile-abandonment post

### ISSUE THREAD

**Issue by philipwalton** [tkadlec/WPOStats#41]
Can you please remove the [2016-09-15-google-mobile-abandonment.markdown](https://github.com/tkadlec/WPOStats/blob/master/_posts/2016-09-15-google-mobile-abandonment.markdown) from this site?

This stats is a misleading because the way it is phrased in the report doesn't accurately reflect the results of the study.

I (and some people on my team) dug into the methodology of this study a bit last year and it turns out that the 53% number wasn't a measure of _abandonment_ rate but rather a measure of _bounce rate_. In some cases a bounce can also be an abandon, but in many cases it is not. A user may visit a site, read what they came there to read, and then leave—happy with the experience. In this study, _those_ users were included in the 53% number (because technically those sessions were bounces).

We've had some internal discussion at Google, and as a result of that discussion, this stat is no longer approved for use by marketing, so I think it makes sense to remove it from this site as well.

I'm happy to provide more details if you're interested.

**Comment by RByers** [comment]
+1 - this is a bad stat and the pretty extreme sounding stat makes legitimate ones look weak by comparison.

**Comment by tkadlec** [comment]
Thanks @philipwalton @RByers. Removed.
