### ISSUE TITLE
Study Submission: The Impact of Web Performance

### ISSUE THREAD

**Issue by charlespwd** [tkadlec/WPOStats#43]
## Key Takeaway
Rendering performance on Single Page Apps is more important than Page Speed when it comes to conversion. So much that users who have a smooth experience convert 327% more than users who don't.

## Story Source
https://simplified.dev/performance/impact-of-web-performance

## Year published
2020

## Tags
- revenue
- conversion

**Comment by tkadlec** [comment]
Sorry for the delay, @charlespwd. This is up now! https://wpostats.com/2020/05/27/aldos-revenue-rendering.html

Thanks for submitting it!
