### ISSUE TITLE
Study Submission: The Science Behind Web Vitals

### ISSUE THREAD

**Issue by anniesullie** [tkadlec/WPOStats#45]
## Key Takeaway
A Google study over millions of page impressions found that when a site meets the recommended thresholds for the Core Web Vitals metrics, users are at least 24% less likely to abandon a page before it finishes loading.

## Story Source
https://blog.chromium.org/2020/05/the-science-behind-web-vitals.html

## Year published
2020

## Tags
- abandonment

**Comment by tkadlec** [comment]
Thanks, @anniesullie! Closed with 1a85c6793be3183b6cc5d3afc121adfcb8bae7c1
