### ISSUE TITLE
Study Submission: SportsShoes.com

### ISSUE THREAD

**Issue by davepeiris** [tkadlec/WPOStats#46]
## Key Takeaway
SportsShoes.com found that faster-than-average mobile visits were 41% more likely to convert.

## Story Source
https://www.propellernet.co.uk/the-impact-of-speed-on-ecommerce/

## Year published
2020

## Tags
- conversion
- revenue

**Comment by tkadlec** [comment]
Ooo....this is great @davepeiris! (Sorry...somehow didn't see/get a notification on this so just noticing now.)

To be clear, is that 41% more likely than slower-than-average visits? Or than the average? I read the post, but it wasn't clear to me.

**Comment by davepeiris** [comment]
Thanks Tim! I should update that post and make it clearer - it's 41% more likely to convert vs slower-than-average visits.
