### ISSUE TITLE
Study Submission: Online Controlled Experiments at Large Scale

### ISSUE THREAD

**Issue by bantmen** [tkadlec/WPOStats#47]
## Key Takeaway
Bing observed that an engineer that improves server performance by 10ms (that’s 1/30 of the speed that our eyes blink) more than pays for his fully-loaded annual costs. Every millisecond counts.

## Story Source
http://www.robotics.stanford.edu/users/ronnyk/2013%20controlledExperimentsAtScale.pdf

## Year published
2013

## Tags
- 2013
- server
- search
- revenue

**Comment by tkadlec** [comment]
Thanks @bantmen! Sorry it took so long to get to this, but it's live. https://wpostats.com/2021/01/20/bing-improvement-engineer-cost.html

**Comment by bantmen** [comment]
Thank you!
