### ISSUE TITLE
Study Submission:

### ISSUE THREAD

**Issue by andydavies** [tkadlec/WPOStats#48]
## Key Takeaway
Bridesmaid dress retailer Revelry relaunched its ecommerce site on an updated version of its ecommerce platform and with smaller images. The site loads 43% faster, bounce rates have decreased 8% and conversion is up 30%

## Story Source
https://www.digitalcommerce360.com/2020/09/22/revelrys-bounce-rate-plummets-with-faster-site/

## Year published
2020

## Tags
- bounce rate
- conversion

**Comment by tkadlec** [comment]
Thanks, @andydavies !

Funnily enough, I read that one and thought I had added it, but guess not! It's up now thanks to 48266c2.
