### ISSUE TITLE
Case Study Submission: A Place For Mom

### ISSUE THREAD

**Issue by KateGhostery** [tkadlec/WPOStats#5]
## Key Takeaway
_A Place For Mom Speeds Up Site And Cuts Average Tag Latency By Over 40%_

## Story Source
_https://www.ghostery.com/why-ghostery/success-stories/APFM/_

## Year published
_2015_
## Tags
- Data governance
- Customer data management
- Tag manager
- Website performance

**Comment by tammyeverts** [comment]
I like this case study, but would love to see it connect the dots more clearly between perf improvements and UX or business metrics. The piece says "This provided tremendous positive impact for SEO - a core asset for driving new leads." Is there any data around this? Or any other quantified UX/biz metric?

**Comment by KateGhostery** [comment]
Hi - this piece of info came right from the customer. Will dig in to see if we can substantiate with more data.

Thanks!

**Comment by tammyeverts** [comment]
Awesome, thanks!

**Comment by KateGhostery** [comment]
Hi Tammy -

We were not able to get solid data on the positive impact to SEO from the customer...would you consider publishing if we pulled out that benefit? There are still other strong substantiated metrics.

Thanks,
Kate

**Comment by tammyeverts** [comment]
Hi Kate,

As long as there's some kind of measurable impact that we can point to,
then yes, definitely.

Thanks!

Tammy

**Comment by tkadlec** [comment]
Closing this for now. Would LOVE to pull it in at some point if we can make a tie to some sort of key business metric.
