### ISSUE TITLE
Study Submission: Backlinko Core Web Vitals and performance update case study

### ISSUE THREAD

**Issue by CookieDuster** [tkadlec/WPOStats#50]
## Key Takeaway
When Google announced their upcoming Page Experience update, Backlinko realized that they needed to improve their website performance. This is how they did it.

## Story Source
https://bejamas.io/blog/backlinko-case-study/

## Year published
2021

## Tags
- jamstack
- performance
- core web vitals
- headless WordPress

**Comment by tkadlec** [comment]
This is a great post and kudos to the folks involved for making such nice improvements!

The post doesn't mention any business or user engagement metrics—if there's anything like that that can be added, I'd love to link to it from here.

**Comment by CookieDuster** [comment]
We did not want to push those tbh. But overall, page loading speed is 3x faster. The rest of the metrics are not shareable as per client's request.

**Comment by tkadlec** [comment]
Ah, gotcha. 

Love the case study for sure, but WPO Stats focuses specifically on studies that show the business or user engagement impact, so I'll close this one off. If ever a client is willing to share some data, absolutely file another issue so we can get it added.
