### ISSUE TITLE
Study Submission: UPC Business launched a 3 x faster website with Jamstack architecture

### ISSUE THREAD

**Issue by tompeham** [tkadlec/WPOStats#51]
## Key Takeaway
_Knowing about the benefits of Jamstack web development architecture, UPC Business decided to develop a highly customized solution utilizing the power of Jamstack. The new technical stack was the headless CMS Storyblok, the Netlify platform and GitHub._

## Story Source
_`https://www.storyblok.com/cs/upc-business`_

## Year published
2020

## Tags
- 2020
- bounce rate
- conversion
- ads

**Comment by tkadlec** [comment]
Thanks @tompeham! This looks like nice work, but I don't see any business metric improvements being called out in the case study, which is what we'd need to add it here.
