### ISSUE TITLE
Study Submission: Ingram Micro - Improved organic traffic through faster homepage

### ISSUE THREAD

**Issue by shawno** [tkadlec/WPOStats#56]
## Key Takeaway
Ingram Micro saw a 35% increase in Organic traffic by improving homepage TBT by 40%

## Story Source
https://www.speedsense.com/case-study-ingram-micro

## Year published
2022

## Tags
- core web vitals
- engagement
- page views
- search
- seo
- sessions
- traffic

**Comment by shawno** [comment]
Thanks for getting this in Tim!I just checked the link and it’s pouring to the wrong study, the Ingram link should point here: https://www.speedsense.com/case-studies/ingram-microCheers,ShawnOn Mar 7, 2023, at 8:57 AM, tkadlec ***@***.***> wrote:﻿
Closed #56 as completed via 4b0e178.

**Comment by tkadlec** [comment]
Fixed!
