### ISSUE TITLE
Study Submission: Rakuten 24 increased revenue per visitor by ~53%

### ISSUE THREAD

**Issue by twifkak** [tkadlec/WPOStats#61]
## Key Takeaway
Rakuten 24 ran an A/B test on Core Web Vitals improvements and saw an improvement of:

- 53.37% in revenue per visitor.
- 33.13% in conversion rate.
- 15.20% in average order value.
- 9.99% in average time spent.
- A 35.12% reduction in exit rate.

## Story Source
https://web.dev/rakuten/

## Year published
2022

## Tags
- core web vitals
- engagement
- page views

**Comment by tkadlec** [comment]
Sorry for the delay! Should be added with f67d506
