### ISSUE TITLE
Study Submission: How Sunday Citizen improved conversions by focusing on performance

### ISSUE THREAD

**Issue by krzksz** [tkadlec/WPOStats#63]
## Key Takeaway
> Sunday Citizen improved their key performance metrics and were able to achieve 25% improvement in Largest Contentful Paint and 61% in Cumulative Layout Shift at the 75th percentile. This resulted in 4% decrease in bounce rate and over 6% increase in conversion.

## Story Source
https://performance.shopify.com/blogs/blog/how-sunday-citizen-improved-conversions-by-focusing-on-performance

## Year published
2022

## Tags
- bounce rate
- conversion rate
- core web vitals
- 2022

**Comment by tkadlec** [comment]
Sorry for the delay! Added in [9061eb5](https://github.com/tkadlec/WPOStats/commit/9061eb5b8022d1babaac52af2788441333b82449)
