### ISSUE TITLE
ft.com

### ISSUE THREAD

**Issue by commuterjoy** [tkadlec/WPOStats#8]
## Key Takeaway

Financial Times added a one second delay to every page view and saw a 4.9% drop in the number of articles users read over a 7 day window. A two-second delay resulted in a 4.4% drop, and a three second delay saw a 7.2% drop. After twenty-eight days the two and three second variants both resulted in further drops in engagement.

## Story Source

- http://engineroom.ft.com/2016/04/04/a-faster-ft-com/

## Tags

- revenue
- publishing
- engagement
- 2016

**Comment by tkadlec** [comment]
Posted. http://engineroom.ft.com/2016/04/04/a-faster-ft-com/

Thanks!
