### ISSUE TITLE
Newspaper sites give "slow news day" new meaning

### ISSUE THREAD

**Issue by hearvox** [tkadlec/WPOStats#9]
Performance tests on the sites of all (1400+) US newspaper dailies and alt-weeklies:

Need for speed 1: Newspaper load times give ‘slow news day’ new meaning
"Dear newspaper publisher: Why is your site so slow? It's still loading and I'm still waiting. Nevermind, I'll just get my news somewhere else..."
https://www.rjionline.org/stories/need-for-speed-1-newspaper-load-times-give-slow-news-day-new-meaning

**Comment by tkadlec** [comment]
This is so good! However, I didn't see a direct stat here to reference. @tammyeverts what do you think?

**Comment by hearvox** [comment]
Tim, glad you liked the research. After I submitted here, however, I realized it doesn't quite match other WPO Stats articles. While it "demonstrates the impact of web performance", really it documents more than demonstrates .

As far a stat tho: The average website loads in about 5 seconds. The average newspaper site take 17 seconds to load, more than three time slower. 

Compared to the Top 1000 sites, newspapers have almost three times the HTTP requests and more than double the page weight.

(The above stuff is in the top table, but in retrospect, I should have stated this in the article text.)

Anyroad: It'd be incredible if you could include my research in WPO Stats, but I understand if it's not quite what you list.

BTW, at risk of boring the living fuq out of y'all, what was also interesting in the data was the very strong correlation of page-load times with #-of-requests and page-weight, but much weaker connection to things like Google PageSpeed score and #-of-widgets (and almost no correlation with #-of-DOM-elements or Alexa Page Rank). The follow-up post on methodologies has a table of correlations: https://www.rjionline.org/stories/need-for-speed-2-newspaper-data-diving-metrics-and-methodologies

Lastly, Tim, love your work, It was very much part of the inspiration that lead me to dive into this data.

**Comment by tkadlec** [comment]
I think it's not quite the right fit for WPO Stats, but it's killer research! Keep up the solid work! 👍
